mock_posts = [
    {
        "id": "post-1",
        "title": "O menino do pijama listrado",
        "figure": "https://drive.google.com/uc?export=view&id=19vFQuZVsaSP6XxJXzgL4BTPzCk31D0FK",
        "autor": "John Boyne",
    },
    {
        "id": "post-2",
        "title": "O Pequeno Príncipe",
        "figure": "https://drive.google.com/uc?export=view&id=1ngPcSkdNwVxGBBH_ZTcQNjOPLmX3ki_g",
        "autor": "Antoine de Saint-Exupéry",
    },
    {
        "id": "post-3",
        "title": "Torto Arado",
        "figure": "https://drive.google.com/uc?export=view&id=1609-ZatpcRVeAEjdzm2OvzSLVhHPLR1M",
        "autor": "Itamar Vieira Junior",
    },
    {
        "id": "post-4",
        "title": "Orgulho e Preconceito",
        "figure": "https://drive.google.com/uc?export=view&id=1JLpmQKrc75P2l83K_YEb0P0Pbt8wOJDT",
        "autor": "Jane Austen",
    },
    {
        "id": "post-5",
        "title": "A Menina que Roubava Livros",
        "figure": "https://drive.google.com/uc?export=view&id=19PhsR5r8Iq4i8gXEl5S6h6lWy8Kzalpr",
        "autor": "Markus Zusak",
    },
    {
        "id": "post-6",
        "title": "Bíblia Sagrada",
        "figure": "https://drive.google.com/uc?export=view&id=1g7ClpG8USWP2axjYwTj0i7dh57tWma3p",
        "autor": "Diversos autores",
    },
    {
        "id": "post-7",
        "title": "Corte de Espinhos e Rosas",
        "figure": "https://drive.google.com/uc?export=view&id=1pAtnE4JlYXtipUlBJbh0kgy684gQQolV",
        "autor": "Sarah J. Maas",
    },
    {
        "id": "post-8",
        "title": "O Livro da Lua 2025",
        "figure": "https://drive.google.com/uc?export=view&id=15_-VUvKXJZJB9fWVyCxYppplxt8KrFJW",
        "autor": "Márcia Mattos",
    },
    {
        "id": "post-9",
        "title": "Never Flinch",
        "figure": "https://drive.google.com/uc?export=view&id=1gXQqbFyOi5A7gQJV5KklhTYN50Xnv-zN",
        "autor": "Stephen King",
    },
    {
        "id": "post-10",
        "title": "O Ministério do Tempo",
        "figure": "https://drive.google.com/uc?export=view&id=1jOPLHf9Ohy7KG6ND1xDgfxbhDy3GxD7D",
        "autor": "Kaliane Bradley",
    },
    {
        "id": "post-11",
        "title": "Tormenta",
        "figure": "https://drive.google.com/uc?export=view&id=1QNI4nPXBVDfYWidjPt1UyQrpYI6P5hYp",
        "autor": "C.J. Tudor",
    },
    {
        "id": "post-12",
        "title": "Tempestade de Ônix",
        "figure": "https://drive.google.com/uc?export=view&id=1qYOsmK0EWm-hBdR-4WS7sc4eUylHP_Mz",
        "autor": "Rebecca Yarros",
    },
    {
        "id": "post-13",
        "title": "Esperança para um novo dia",
        "figure": "https://drive.google.com/uc?export=view&id=1-AaCEXnMdobraxIKY6y2_noSL4OalFSK",
        "autor": "Mensagens de fé",
    },
    {
        "id": "post-14",
        "title": "Um destino tatuado em sangue",
        "figure": "https://drive.google.com/uc?export=view&id=1EZlZuf7FUTTwdJRf9y72dlv23nUK6J71",
        "autor": "Danielle L. Jensen",
    },
    {
        "id": "post-15",
        "title": "A cinco passos de você",
        "figure": "https://drive.google.com/uc?export=view&id=17G7Rd0a9tVV9vODX4obq-oJJ8n0LAmfP",
        "autor": "Rachael Lippincott",
    },
    {
        "id": "post-16",
        "title": "A Biblioteca da Meia-Noite",
        "figure": "https://drive.google.com/uc?export=view&id=1SwyFrVSNI_WGyVlGX4FZZLCV5csyaQ0l",
        "autor": "Matt Haig",
    },
    {
        "id": "post-17",
        "title": "A Culpa é das Estrelas",
        "figure": "https://drive.google.com/uc?export=view&id=1k0_DdHVW-Y_XTCnsia35IHUxQuZ4aC79",
        "autor": "John Green",
    },
    {
        "id": "post-18",
        "title": "Os Sete Maridos de Evelyn Hugo",
        "figure": "https://drive.google.com/uc?export=view&id=1FgqCc2zDNWdWgbDVyxrR0g83vSCN444h",  # local image
        "autor": "Taylor Jenkins Reid",
    },
    {
        "id": "post-19",
        "title": "É assim que acaba",
        "figure": "https://drive.google.com/uc?export=view&id=1qB4umKZNZFm9wDoEtWY1qAme7N62j7Mb",
        "autor": "Colleen Hoover",
    },
    {
        "id": "post-20",
        "title": "Café com Deus Pai",
        "figure": "https://drive.google.com/uc?export=view&id=15Y4fvVPU51zv0kSLsp8QLXe6qTltnP1R",
        "autor": "Junior Rostirola",
    },
    {
        "id": "post-21",
        "title": "Flores para Algernon",
        "figure": "https://drive.google.com/uc?export=view&id=1O0fL003QVSwNAA1d_c5mqXQkZ6a9dBeH",
        "autor": "Daniel Keyes",
    },
]
